# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

# - master

pool:
  name: 'mi pc VS2022'

variables:
  buildConfiguration: 'Release'

stages:
- stage: FrameworkAndPackages
  displayName: 'Frameworks and packages'

  jobs:
    - job: FrameworkJob
      steps:
      - task: UseDotNet@2
        inputs:
          version: '6.x'

      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet 6.0.0'
        inputs:
          versionSpec: 6.0.0    

- stage: RestoreAndBuild
  displayName: 'Restore And Build'

  jobs:
    - job: RestoreAndBuildJob
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'select'
          projects: '$(Build.SourcesDirectory)/pipelines-dotnet-core.csproj'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          workingDirectory: '$(Build.SourcesDirectory)'
        displayName: 'dotnet build $(buildConfiguration)'

- stage: Publish
  displayName: 'Publish'

  jobs:
    - job: PublishJob
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Publish Version'
        inputs:
          command: publish
          projects: '$(Build.SourcesDirectory)/pipelines-dotnet-core.csproj'
          publishWebProjects: false
          arguments: '--configuration $(buildConfiguration) -r win-x64 --self-contained true --output $(Build.ArtifactStagingDirectory)/PipelinesDotNetCore'

      - publish: '$(Build.ArtifactStagingDirectory)/PipelinesDotNetCore'
        artifact: drop
